# Generated by Django 5.2.4 on 2025-08-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(default='sem marca', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
