# Generated by Django 5.2.4 on 2025-08-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_produto_marca_delete_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_servico',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa de serviço adicional para o pedido', max_digits=10),
        ),
    ]
