# Generated by Django 5.2.4 on 2025-08-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pedido_valor_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproduto',
            name='preco_venda_unitario',
        ),
        migrations.AddField(
            model_name='pedidoproduto',
            name='custo_real_item_unidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidoproduto',
            name='margem_venda_unitaria',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor adicionado ao custo do produto (lucro por unidade)', max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.IntegerField(default=0, help_text='Quantidade disponível em estoque'),
        ),
    ]
